trigger:
  branches:
    include:
    - master
  paths:
    include:
    - GolfDashboard.Web

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: PowerShell@2
  displayName: Build
  env:
    NODE_OPTIONS: --max_old_space_size=16384
    
- script: |
    npm ci
    npm run build
  displayName: 'npm install and build'
  workingDirectory: 'GolfDashboard.Web'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './GolfDashboard.Web/build'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Zip build folder'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'BuildOutput'
    publishLocation: 'Container'